### Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123"
}

### get user by token
GET http://localhost:8080/api/auth/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyOTMxNDE5OSwiZXhwIjoxNzI5NDAwNTk5fQ.gKU7UyBbCSyl0OpIYRyWAe3MEcZgo_2aCk27FdUMybc
### Login with token
POST http://localhost:8080/api/auth/login HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyOTMxNDE5OSwiZXhwIjoxNzI5NDAwNTk5fQ.gKU7UyBbCSyl0OpIYRyWAe3MEcZgo_2aCk27FdUMybc

### Register
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "trung@gmail.com",
    "password": "123",
    "username": "trung",
    "phoneNumber": "0123456789"
}

### get book by id
GET http://localhost:8080/api/book/1 HTTP/1.1

### Update book
POST http://localhost:8080/api/book/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTcyOTA4Njg2NywiZXhwIjoxNzI5MTczMjY3fQ.JqO5fko7PHToozpb1VQJ4zNcYdXbhx5grbhjksm-b74
Content-Type: application/json

{
  "discount_id": 2
}

### Create book
POST http://localhost:8080/api/book/create HTTP/1.1
# Authorization: 

### Get book page
GET http://localhost:8080/api/book?page=1&limit=10&sortBy=publisher HTTP/1.1

### lay tat ca gia tri trong combo box form them sach
GET http://localhost:8080/api/book/reference/all HTTP/1.1

### get page purchase
GET http://localhost:8080/api/purchase?page=1&limit=10 HTTP/1.1

### get purchase by id
GET http://localhost:8080/api/purchase/7 HTTP/1.1

### create purchase
POST http://localhost:8080/api/purchase HTTP/1.1
Content-Type: application/json

{
  "provider_id": 1,
  "purchase_date": "2021-08-17",
  "purchaseDetails": [
    {
      "book_id": 1,
      "quantity": 10,
      "price": 100000
    },
    {
      "book_id": 2,
      "quantity": 10,
      "price": 100000
    }
  ]
}

### get all provider
GET http://localhost:8080/api/provider/all HTTP/1.1

###get page account
GET http://localhost:8080/api/account?page=1&limit=10 HTTP/1.1

### thong ke nhap hang
GET http://localhost:8080/api/thongke/receipts HTTP/1.1

### thong ke truy cap
GET http://localhost:8080/api/thongke/accession?fromDate=2024-01-01&toDate=2025-01-01 HTTP/1.1

### thong ke doanh thu, loi nhuan
GET http://localhost:8080/api/thongke/revenue?fromDate=2024-01-01&toDate=2025-01-01 HTTP/1.1

### thong ke sach ban chay
GET http://localhost:8080/api/thongke/sale-trending?fromDate=2024-11-26&toDate=2025-01-01 HTTP/1.1

### dat hang
POST http://localhost:8080/api/order HTTP/1.1
Content-Type: application/json

{
  "customer_id": 2,
  "address": "123 abc",
  "orderDetails": [
    {
      "book_id": 1,
      "quantity": 10,
      "discount_id": 1
    }
  ]
}

### chua lam
### xem chi tiet don hang
GET http://localhost:8080/api/order/1 HTTP/1.1

### chuyen trang thai don hang
POST http://localhost:8080/api/order/1 HTTP/1.1
Content-Type: application/json

{
  "status": 1
}

### get page discount
GET http://localhost:8080/api/discounts HTTP/1.1

### get page promotion
GET http://localhost:8080/api/bill-promotion HTTP/1.1

### create promotion
POST http://localhost:8080/api/bill-promotion HTTP/1.1
Content-Type: application/json

{
  "promotion": {
    "conditional": 200000,
    "type": "Truc tiep",
    "value": 30000,
    "start_at": "2021-08-17",
    "end_at": "2021-08-17",
    "name": "abc"
  }
}

### update promotion
POST http://localhost:8080/api/bill-promotion/1 HTTP/1.1
Content-Type: application/json

{
  "promotion": {
    "conditional": 200000,
    "type": "Truc tiep",
    "value": 30000,
    "start_at": "2021-08-17",
    "end_at": "2021-08-17",
    "name": "abc"
  }
}

### get order detail
GET http://localhost:8080/api/order/detail/3 HTTP/1.1

### get all bill promotion
GET http://localhost:8080/api/promotion/bill-promotion HTTP/1.1

### get all discount
GET http://localhost:8080/api/promotion/discount HTTP/1.1

### get all genres
GET http://localhost:8080/api/promotion/genre HTTP/1.1